#define NUM_COLL 13
#define NUM_ROW 4
#define NUM_PINS NUM_ROW+NUM_COLL
#define NUM_KEYS NUM_COLL*NUM_ROW
#define NUM_LAYERS 3
#define LAYER_VALUE 0,1,2

#define HOLD_SLEEP 150

#define DOUBLETAP_TAP_DELAY  100
#define DOUBLETAP_RELEASE_DELAY 100

#define DTAPHOLD_RELEASE_DELAY 100
#define DTAPHOLD_TAP_DELAY  100
